name: "Lint PR"

on: [pull_request]

permissions:
  pull-requests: read

jobs:
  lint-pr:
    runs-on: ubuntu-latest
    steps:
    - name: Validate PR title
      uses: amannn/action-semantic-pull-request@v5
      with:
        # Configure types according to your needs
        types: |
          feat
          fix
          docs
          style
          refactor
          perf
          test
          build
          ci
          chore
          revert
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}